name: Release Actions

on:
  release:
    types: [published]

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest
    steps:
    - name: Translate Repo Name For Build Tools filename_prefix
      id: repo-name
      run: |
        echo "repo-name=$(
        echo ${{ github.repository }} |
        awk -F '\/' '{ print tolower($2) }' |
        tr '_' '-'
        )" >> $GITHUB_OUTPUT
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Versions
      run: |
        python3 --version
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Fetch correct submodule shas
      run: git submodule foreach 'git fetch --tags --depth 1 origin $sha1 && git checkout -q $sha1'
    - name: Install deps
      run: |
        sudo apt-get install -y gettext gawk
        pip install -r requirements.txt
    - name: Build assets
      run: circuitpython-build-bundles --filename_prefix ${{ steps.repo-name.outputs.repo-name }} --library_location qwiic/drivers --library_depth 1 --package_folder_prefix "Qwiic, qwiic, Pi"
    - name: Upload Release Assets
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        asset_path: "bundles/*"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        upload_url: ${{ github.event.release.upload_url }}